import type { Locale } from "@/lib/i18n";

export type ManualSection = {
  title: string;
  body: string;
  bullets: string[];
};

export type ManualHelpBlock = {
  title: string;
  body: string;
  bullets: string[];
  href?: string;
  cta?: string;
};

export function getSsiPublicManual(locale: Locale) {
  const uk = locale === "uk";

  return {
    eyebrow: uk ? "SPIKE manual" : "SPIKE manual",
    title: uk ? "Як користуватися SPIKE Spot Index" : "How to use SPIKE Spot Index",
    intro: uk
      ? "Короткий операційний довідник для користувачів, респондентів і партнерів SSI. Він оновлюється разом із функціональними, текстовими та інтерфейсними змінами продукту."
      : "A concise operating guide for SSI users, respondents and partners. It is updated together with functional, copy and interface changes in the product.",
    sections: [
      {
        title: uk ? "Що публікує SSI" : "What SSI publishes",
        body: uk
          ? "SPIKE Spot Index публікує методологічні індекси українського аграрного spot market. Значення індексу не генерується AI: воно розраховується з респондентських, Monitor/MN7R та перевірених адміністративних даних."
          : "SPIKE Spot Index publishes methodology-based Ukrainian agricultural spot market indices. Index values are not generated by AI: they are calculated from respondent, Monitor/MN7R and verified administrative data.",
        bullets: uk
          ? ["Grains Export — зернові експортні позиції.", "Oilseeds Export — сезонні олійні експортні позиції.", "Oilseeds Crush — внутрішній ринок переробки з VAT-inclusive логікою."]
          : ["Grains Export — grain export positions.", "Oilseeds Export — seasonal oilseed export positions.", "Oilseeds Crush — domestic processing market with VAT-inclusive logic."],
      },
      {
        title: uk ? "Як читати аналітику" : "How to read analytics",
        body: uk
          ? "Analytics пояснює вже опубліковані індекси: динаміку, волатильність, спреди, групи товарів і архів з 2025-09-01 для основних позицій."
          : "Analytics explains already published index values: movement, volatility, spreads, commodity groups and the archive from 2025-09-01 for core positions.",
        bullets: uk
          ? ["AI Market Read показує 30 останніх опублікованих днів і окремо позначену сезонну траєкторію на наступні 30 днів за трьома попередніми роками.", "Якщо у день немає ціни для спреду, використовується останнє доступне значення.", "AI Market Read є публічним preview аналітичного шару, а не торговою рекомендацією."]
          : ["AI Market Read shows the last 30 published days and a separately labelled 30-day seasonal path based on the three prior years.", "If a spread price is missing for a date, the latest available value is carried forward.", "AI Market Read is a public preview of the analytical layer, not a trading recommendation."],
      },
      {
        title: uk ? "Що таке Context" : "What Context does",
        body: uk
          ? "Context окремо моніторить Telegram, RSS/API news, ручні матеріали редактора і файли, а потім формує daily / weekly / monthly контекст навколо ринку та руху індексів."
          : "Context separately monitors Telegram, RSS/API news, editor-submitted materials and files, then turns them into daily / weekly / monthly context around the market and index movement.",
        bullets: uk
          ? ["Daily report виходить після публікації індексу.", "Weekly/monthly report виходить у суботу і замінює daily у цей день.", "У Telegram SSI daily містить індекси дня + стислий індексний дайджест."]
          : ["Daily report is published after the index publication.", "Weekly/monthly report is published on Saturday and replaces daily on that day.", "SSI Telegram daily contains daily indices plus a concise index digest."],
      },
      {
        title: uk ? "Для респондента" : "For respondents",
        body: uk
          ? "Респондент отримує onboarding email, встановлює постійний пароль, стартує SPIKE Telegram bot і далі отримує форму за розкладом."
          : "A respondent receives an onboarding email, sets a permanent password, starts the SPIKE Telegram bot and then receives the survey form on schedule.",
        bullets: uk
          ? ["Telegram-запит: 16:00 Kyiv.", "Reminder: 17:00 Kyiv.", "Фінальний розрахунок і публікація: 19:00 Kyiv у будні дні."]
          : ["Telegram request: 16:00 Kyiv.", "Reminder: 17:00 Kyiv.", "Final calculation and publication: 19:00 Kyiv on weekdays."],
      },
    ] satisfies ManualSection[],
  };
}

export function getSsiAdminManual() {
  return {
    eyebrow: "SSI operations",
    title: "Admin manual",
    intro:
      "Operational SSI guide for administrators. Keep this content updated whenever functionality, naming, UI or publication logic changes.",
    sections: [
      {
        title: "Daily publication schedule",
        body:
          "Respondent Telegram collection happens before the publication window. Index publication and Context generation are separated from respondent reminders.",
        bullets: [
          "16:00 Kyiv — initial respondent Telegram request.",
          "17:00 Kyiv — respondent reminder.",
          "17:00 Kyiv — MN7R/Monitor import window.",
          "19:00 Kyiv — final index calculation, public index publication, Context daily generation and Telegram publishing.",
        ],
      },
      {
        title: "Respondent checks",
        body:
          "Use Respondents to verify onboarding, password status, Telegram linkage, latest delivery status and submitted values.",
        bullets: [
          "TG failed before /start usually means Telegram cannot deliver to the chat yet.",
          "telegram_bot_start with sent status means the bot is linked.",
          "temporary password status means the user has not set a permanent password yet.",
          "If values are submitted, scheduled reminders for the same trade date should stop for that respondent.",
        ],
      },
      {
        title: "Index workflow",
        body:
          "Use Daily input for raw values and Publish SPIKE SPOT INDEX for calculation/publish. Published values should remain locked unless an admin deliberately unlocks the current Kyiv trade date.",
        bullets: [
          "One valid value is enough to publish a position.",
          "Multiple values are averaged after validation logic.",
          "Missing public values should fall back to the latest available value where this is explicitly intended for charts.",
        ],
      },
      {
        title: "Context workflow",
        body:
          "Context uses monitoring sources, manual Telegram/admin materials, files, index data and LLM summarization. Reports should not publish empty sections or 'data unavailable' filler.",
        bullets: [
          "Daily SSI report is Ukrainian-first and tied to the day’s index movement.",
          "1D3X reports use global English monitoring and its own Telegram bot/chat configuration.",
          "Manual materials can be sent with #ssi, #1d3x, #daily, #weekly or #monthly tags.",
        ],
      },
      {
        title: "Manual maintenance rule",
        body:
          "Any functional, naming, UI, schedule or publication change must update this manual source in the same PR/commit.",
        bullets: [
          "Update public manual if the user/respondent behavior changes.",
          "Update admin manual if the operator workflow changes.",
          "Update contextual help blocks when an individual screen changes.",
        ],
      },
    ] satisfies ManualSection[],
  };
}

export function getSsiHelpBlock(area: "analytics" | "mediaHub" | "adminRespondents" | "adminMediaHub" | "adminDailyInput", locale: Locale = "en"): ManualHelpBlock {
  const uk = locale === "uk";
  const publicHref = `/${locale}/manual`;

  const blocks: Record<typeof area, ManualHelpBlock> = {
    analytics: {
      title: uk ? "Як читати цей блок" : "How to read this block",
      body: uk
        ? "Analytics пояснює опубліковані індекси: рух, волатильність, спреди та групову динаміку. Це не прогноз і не trading signal."
        : "Analytics explains published indices: movement, volatility, spreads and group dynamics. It is not a forecast or trading signal.",
      bullets: uk
        ? ["Дані базуються на опублікованому архіві.", "AI Market Read є публічним preview.", "Context відповідає за новинний контекст."]
        : ["Data is based on the published archive.", "AI Market Read is a public preview.", "Context covers the news context."],
      href: publicHref,
      cta: uk ? "Відкрити manual" : "Open manual",
    },
    mediaHub: {
      title: uk ? "Context коротко" : "Context in short",
      body: uk
        ? "Context моніторить джерела і формує daily / weekly / monthly контекст. На SSI він пояснює, що могло впливати на ринок і рух індексів."
        : "Context monitors sources and generates daily / weekly / monthly context. On SSI it explains what may have influenced the market and index movement.",
      bullets: uk
        ? ["Daily — після публікації індексу.", "Weekly/monthly — у суботу.", "Monitoring feed залишається сирим джерельним шаром."]
        : ["Daily — after index publication.", "Weekly/monthly — on Saturday.", "Monitoring feed remains the raw source layer."],
      href: publicHref,
      cta: uk ? "Відкрити manual" : "Open manual",
    },
    adminRespondents: {
      title: "Respondent operations",
      body: "Check onboarding, password, Telegram link and delivery state before treating a red badge as a real failure.",
      bullets: ["TG failed + no chat id means the bot was not linked yet.", "telegram_bot_start means Telegram is linked.", "temporary password means the user has not completed password setup."],
      href: "/admin/manual#respondent-checks",
      cta: "Open admin manual",
    },
    adminMediaHub: {
      title: "Context operations",
      body: "Use this area for monitoring windows, source/material intake and daily/weekly/monthly report publication control.",
      bullets: ["Avoid empty report sections.", "Manual materials strengthen weekly/monthly reports.", "Telegram tags route materials to SSI and/or 1D3X."],
      href: "/admin/manual#mediahub-workflow",
      cta: "Open admin manual",
    },
    adminDailyInput: {
      title: "Daily input rule",
      body: "Daily input is the data workspace before publication. Respondent collection must happen before the 19:00 Kyiv publish slot.",
      bullets: ["One valid value can publish a position.", "Review missing values before calculation.", "Published values are locked after publication."],
      href: "/admin/manual#index-workflow",
      cta: "Open admin manual",
    },
  };

  return blocks[area];
}
